# # This workflow is for scraping data from the OCC website on a weekly basis
# name: meat_telegram

# # Controls when the action will run.
# on:
#   # Action can be manually started
#   workflow_dispatch:
#   # job runs on Mon and Tues mornings 
#   schedule:
#     - cron: '0 15 * * 1'
#     - cron: '0 13 * * 2'

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "scrape"
#   get_meat:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - name: Check out this repository
#         uses: actions/checkout@v2
#       # - name: Install Chromium on ubuntu box
#       #   run: sudo apt-get install -y chromium-browser
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9'
      # - name: Install all necessary packages
      #   run: pip install bs4 telegram-send requests lxml

      #   # Run the Python script
      # - name: Run Python script
      #   run: python3 main.py

#       #   # Commit .csv result to repo
#       # - name: Add Data
#       #   run: |-
#       #     git config user.name "Automated"
#       #     git config user.email "actions@users.noreply.github.com"
#       #     git add -A
#       #     timestamp=$(date -u)
#       #     git commit -m "Latest data: ${timestamp}" || exit 0
#       #     git push


name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install all necessary packages
        run: pip install bs4 telepot requests lxml

        # Run the Python script
      - name: Run Python script
        run: python main.py