
name: meat_telegram

# Controls when the action will run.
on:
  # Action can be manually started
  workflow_dispatch:
  # job runs on Mon and Tues mornings 
  schedule:
    - cron: '0 15 * * 1'
    - cron: '0 13 * * 2'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install pipenv
        run: pip install pipenv

      - name: Install deps
        run: pipenv install

      # - name: Install all necessary packages
      #   run: pip install bs4 telepot requests lxml

        # Run the Python script
      - name: Run Python script
        run: pipenv run python main.py ${{ secrets.API_KEY }}
